import dynamic from "next/dynamic";
import 'bootstrap/dist/css/bootstrap.min.css';
import "@/styles/globals.scss";
import Header from "@/components/header";
import { ThemeProvider } from "@/context/ThemeContext";


const BodyWithTheme = dynamic(() => import("@/components/BodyWithTheme"), {
  ssr: true,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <BodyWithTheme>
          <Header>
          {children}
          </Header>
        </BodyWithTheme>
      </ThemeProvider>
    </html>
  );
}
